# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
